In [ ]:
# 100 Numpy Exercises 

In [1]:
# 1. Import the numpy package under the name np (★☆☆)
import numpy as np

In [2]:
# 2. Print the numpy version and the configuration (★☆☆)

print(np.show_config)
print(np.__version__)       # double underscore

<function show at 0x7f57f4543670>
1.20.1


In [3]:
# 3. Create a null vector of size 10 (★☆☆)

a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 4. How to find the memory size of any array (★☆☆)

a = np.arange(10)
print(a)
print(a.size * a.itemsize)

[0 1 2 3 4 5 6 7 8 9]
80


In [5]:
# 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)

a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# 8. Reverse a vector (first element becomes last) (★☆☆)

a1 = np.arange(10)
a1 = a1[::-1]
print(a1)

[9 8 7 6 5 4 3 2 1 0]


In [9]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

a2 = np.arange(9).reshape(3,3)
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

a = np.nonzero([1,2,0,0,4,0])    # it gives the index values of non-zero in o/p
print(a)

(array([0, 1, 4]),)


In [11]:
# 11. Create a 3x3 identity matrix (★☆☆)

a2 = np.eye(3)
print(a2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# 12. Create a 3x3x3 array with random values (★☆☆)

b = np.random.random((3,3,3))
print(b)

[[[0.24603521 0.44818209 0.13969117]
  [0.17563044 0.94172274 0.52050885]
  [0.90000436 0.47042537 0.18788946]]

 [[0.2792719  0.69303757 0.53553344]
  [0.83974851 0.28163835 0.77416167]
  [0.68586391 0.70647867 0.19501407]]

 [[0.90469753 0.60727514 0.24951958]
  [0.73199425 0.79410609 0.81638166]
  [0.29027808 0.56530508 0.80800311]]]


In [13]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

c = np.random.random((10,10))
#print(c)
a = c.max()
b = c.min()
print("Maximum value is ",a)
print("Minimum value is ",b)

Maximum value is  0.9845526230669672
Minimum value is  0.007903799882077234


In [14]:
# 14. Create a random vector of size 30 and find the mean value (★☆☆)

a1 = np.random.random(30)
#print(a1)
a2 = np.mean(a1)
a3 = a1.mean()
print(a2)
print(a3)

0.5239173805502628
0.5239173805502628


In [15]:
# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

a = np.ones((10,10))
a[1:-1 , 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

a = np.ones((10,10))
a[[0,-1] , :] = 0
a[: , [0,-1]] = 0
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [20]:
# 17. What is the result of the following expression? (★☆☆)
       0 * np.nan
       np.nan == np.nan
       np.inf > np.nan
       np.nan - np.nan
       np.nan in set([np.nan])
       0.3 == 3 * 0.1

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [19]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

a1 = np.diag(1+np.arange(4),-1)
print(a1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [23]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern

a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1                             # 1::2 - 1st row 0, 2nd row 1   , ::2 - 1st col 1, 2nd col 0
a[::2,1::2] = 1                             # reverse of the above
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [34]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

a = np.unravel_index(99,(6,7,8))
print(a)

(1, 5, 3)


In [35]:
# 21. Create a checkerboard 8x8 matrix using the tile function 

a = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [40]:
# 22. Normalize a 5x5 random matrix 

a = np.random.random((5,5))
b = (a - np.mean(a))/(np.std(a))
print(b)

[[ 1.21152891 -1.04026239  0.33154018  1.45007994 -0.8978248 ]
 [-1.16396463  1.25074905  0.63388868  0.06710019 -0.57664433]
 [ 0.55484792 -0.63494525  0.94512157 -0.8683847   1.63515483]
 [-0.86253297  1.42764669 -1.10592446  0.67453763 -0.01626046]
 [ 0.34867722  0.31861586 -2.09872099 -0.34567146 -1.23835221]]


In [43]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-43-7b73df228a0d>:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])


In [44]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

a = np.dot(np.ones((5,3)) , np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [47]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. 

a = np.arange(11)
a[(a>3) & (a<8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [48]:
# 26. What is the output of the following script?
print(sum(range(5),-1))

9


In [2]:
# 28. What are the result of the following expressions?
#        np.array(0) / np.array(0)
#        np.array(0) // np.array(0)
#        np.array([np.nan]).astype(int).astype(float)

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-2-13fafc9287a7>:6: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-2-13fafc9287a7>:7: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [52]:
# 30. How to find common values between two arrays?

a = np.arange(8,20,2)
b = np.arange(5,15)
c = np.intersect1d(a,b)
print(c)

[ 8 10 12 14]


In [54]:
# 31. How to ignore all numpy warnings (not recommended)?

defaults = np.seterr(all="ignore")
np.arange(3) / 0

array([nan, inf, inf])

In [56]:
# 32. Is the following expressions true? 

np.sqrt(-1) == np.emath.sqrt(-1)

False

In [57]:
# 33. How to get the dates of yesterday, today and tomorrow? 

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [58]:
# 34. How to get all the dates corresponding to the month of July 2016?

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [70]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods 
#          hint: %, np.floor, astype, np.trunc

Z = np.random.uniform(0,10,10)

print(Z)
print(Z - Z%1)                   # (4.51860838 - 0.51860838 = 4)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


[4.51860838 4.57868804 3.27435184 7.92182085 3.72442332 5.1583793
 4.19949602 2.21388836 5.9471919  0.07693694]
[4. 4. 3. 7. 3. 5. 4. 2. 5. 0.]
[4. 4. 3. 7. 3. 5. 4. 2. 5. 0.]
[4. 4. 3. 7. 3. 5. 4. 2. 5. 0.]
[4 4 3 7 3 5 4 2 5 0]
[4. 4. 3. 7. 3. 5. 4. 2. 5. 0.]


In [79]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 

a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [6]:
# 38. Consider a generator function that generates 10 integers and use it to build an array

def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(), dtype = 'float')        
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [11]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

a = np.linspace(0,1,11, endpoint = False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [12]:
# 40. Create a random vector of size 10 and sort it

a = np.random.random(10)
a.sort()
print(a)

[0.01254917 0.04968601 0.0921237  0.1747594  0.35010386 0.4761085
 0.71847309 0.76476973 0.91820135 0.98962411]


In [13]:
# 41. How to sum a small array faster than np.sum?

a = np.arange(10)
b = np.add.reduce(a)
print(b)

45


In [20]:
# 42. Consider two random array A and B, check if they are equal 

a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

equal = np.array_equal(a,b)
print(equal)

False


In [24]:
# 43. Make an array immutable (read-only)

a = np.arange(10)
a.flags.writeable = False
a[0] = 22
print(a)

ValueError: assignment destination is read-only

In [31]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
#                 hint: np.sqrt, np.arctan2

a = np.random.random((10,2))
x,y = a[:,0],a[:,1]                        # x = all rows in 0th col , y = all rows in 1st col

R = np.sqrt(x**2 + y**2) 
T = np.arctan2(y,x)
print(R)
print(T)

[0.95593387 0.88054011 0.61214421 0.52980749 1.04434971 0.34384518
 0.89501693 0.51323909 0.76338832 0.71528929]
[0.21032942 1.41335853 0.48794929 0.75831581 0.66194166 1.34829507
 0.26660107 0.83538746 1.48588    1.40469189]


In [32]:
# 45. Create random vector of size 10 and replace the maximum value by 0 (hint: argmax)

a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.89988775 0.         0.9177585  0.55671469 0.87592019 0.5182665
 0.28561962 0.01662876 0.2241239  0.163138  ]


In [39]:
# 48. Print the minimum and maximum representable value for each numpy scalar type (hint: np.iinfo, np.finfo, eps)

for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
print()
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)    

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [43]:
# 49. How to print all the values of an array?

np.set_printoptions(threshold=float("inf"))     # optional statement
Z = np.zeros((5,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [44]:
# 51. Create a structured array representing a position (x,y) and a color (r,g,b)

a = np.zeros(10, [('position' , [('x',float,1),('y',float,1)]),
                 ('color' , [('r',float,1),('g',float,1),('b',float,1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-44-6402fea20f0e>:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [('position' , [('x',float,1),('y',float,1)]),


In [45]:
# 54. How to read the following file? (★★☆)
#        1, 2, 3, 4, 5
#        6,  ,  , 7, 8
#         ,  , 9,10,11
#    hint: np.genfromtxt

from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-45-c02ef35778ab>:15: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


In [2]:
# 58. Subtract the mean of each row of a matrix --- hint: mean(axis=,keepdims=)

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)            # Older versions: Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.01841036  0.44941094 -0.36873673  0.07181333  0.22964914 -0.37568869
  -0.21998786  0.37355306 -0.29412552  0.11570196]
 [ 0.50733756  0.13258669 -0.31645655 -0.06549796  0.51872228 -0.35314444
  -0.33970244 -0.23114483 -0.26311081  0.4104105 ]
 [-0.15700355  0.26308833 -0.16692928 -0.08016125 -0.28789213  0.18128503
  -0.14066623  0.16631525  0.30418684 -0.08222302]
 [ 0.01949116 -0.00222886  0.28525171 -0.11152073  0.26533055  0.16307111
   0.38699701 -0.33656173 -0.46303881 -0.2067914 ]
 [ 0.09685489  0.08021172  0.04721324  0.31503297 -0.05382971 -0.41367958
   0.06953062  0.33287443 -0.17441117 -0.29979741]]


In [5]:
# 59. How to sort an array by the nth column? ---- hint: argsort

Z = np.random.randint(0,10,(3,3))
print(Z)
print()
print(Z[Z[:,1].argsort()])

[[3 1 7]
 [6 7 0]
 [7 8 9]]

[[3 1 7]
 [6 7 0]
 [7 8 9]]


In [9]:
# 60. How to tell if a given 2D array has null columns? ----- hint: any, ~

Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[1 0 2 0 1 2 0 0 1 2]
 [2 2 2 1 1 0 1 2 1 1]
 [1 0 0 1 2 1 1 2 1 2]]
False


In [10]:
# 61. Find the nearest value from a given value in an array ---- hint: np.abs, argmin, flat

a = np.random.uniform(0,1,10)
b = 0.5
value = a.flat[np.abs(a - b).argmin()]
print(value)

0.464096331423962


In [11]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list(I)? ---- hint: np.bincount

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]           # index value
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [12]:
# 69. How to get the diagonal of a dot product? -----  hint: np.diag

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.9506089 , 1.39146087, 1.18245405, 1.87632676, 1.07572896])

In [13]:
# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 
#            hint: array[:, :, None]

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [14]:
# 72. How to swap two rows of an array? -----------   hint: array[[]] = array[[]]

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
#74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? hint: np.repeat
    
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [18]:
# 83. How to find the most frequent value in an array? ------ hint: np.bincount, argmax

a = np.random.randint(0,10,50)
value = np.bincount(a).argmax()
print(value)

9
